name: Sharedhosting deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar entorno PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # - name: Install dependencies
      #   run: composer install --no-dev --prefer-dist --no-scripts --no-progress --no-suggest

      # - name: Configure env
      #   env:
      #     FTP_HOST: ${{ secrets.FTPRCDINAL_HOST }}
      #     FTP_USERNAME: ${{ secrets.FTPRCDINAL_USERNAME }}
      #     FTP_PASSWORD: ${{ secrets.FTPRCDINAL_PASSWORD }}
      #     FTP_DESTINATION: ${{ secrets.FTPRCDINAL_DESTINATION }}
      #   run: php artisan config:cache

      - name: Deploy to shared hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTPRCDINAL_HOST }}
          username: ${{ secrets.FTPRCDINAL_USERNAME }}
          password: ${{ secrets.FTPRCDINAL_PASSWORD }}
          server-dir: ${{ secrets.FTPRCDINAL_DESTINATION }}
          
          # exclude: "public/build/**, vendor/**" # Excluir la carpeta build y la carpeta vendor
          exclude: "vendor/**" # Excluir la carpeta build y la carpeta vendor